version: '3.4'

services:
  kudago.telegrambot:
    image: grebenkinanton/kudagotelegrambot:latest
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD} 
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - BOT_TOKEN=${BOT_TOKEN}
  mongodb:
    image: mongo:latest
    restart: always
    env_file:
      - .env
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - /mongodb_data:/data/db
