version: '3.4'

services:
  kudago.telegrambot:
    image: grebenkinanton/kudagotelegrambot:latest
    restart: always
  mongodb:
    image: mongo:latest
    restart: always
    env_file:
      - .env
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - /mongodb_data:/data/db
