version: '3.4'

services:
  kudago.telegrambot:
    image: grebenkinanton/kudagotelegrambot
    restart: always
    build:
      context: .
      dockerfile: src/KudaGo.TelegramBot/Dockerfile
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
